feat: 회원가입 학생인증 페이지
EveryUniv/next-student-council-frontend pull request #16
Opened 2023-09-19 14:04 UTC by sy-paik

**What is this PR?**
- 회원가입 학생인증 페이지(#9 )

**What has changed?**
- swagger api 연결
- 학번과 비밀번호 유효성 검사
- tailwind css 적용
- 라우팅 추가

**A notice to reviewers...**
- constants에 router나 api path 추가해서 연결했는데 통신이 잘 되는지 확인해주세요!

closes #9

2023-09-20 04:02 UTC, ho991217 commented
conflict resolve 해주세요~!

2023-09-20 05:00 UTC, 9ye1 approved these changes
회원가입 학생 인증 페이지 코드 잘 봤습니다!
수연님 코드보고 제가 라우터 설정을 놓친 걸 알았네용
수정해서 다시 커밋해보겠습니다!

2023-09-20 08:16 UTC, 9ye1 approved these changes
회원가입 학생인증 페이지 코드 잘 봤습니다! 
수연님 코드 보고 회원가입 약관동의 페이지 라우터 설정 놓친 걸 알았습니당
오늘 수정 후에 다시 pr 올리겠습니다~!

2023-09-20 09:10 UTC, sy-paik commented on src/constants.ts
> +   SIGNUP_VERIFY: '/user/dku/verify',
40번째줄은 페이지 라우터로 작성한 부분이고 밑에는 api 경로입니다!

2023-09-21 03:02 UTC, ho991217 requested changes

2023-09-21 03:02 UTC, ho991217 commented on src/pages/signup/verify.tsx
> +         const response = await axios.post(SERVER_URL + API_PATH.SIGNUP_VERIFY, verifyInfo);
response dto 구조를 알고있다면 axios에 제네릭 형태로 알려줄 수 있습니다!
예를 들어, signup verify같은 경우
```json
{
  "signupToken": "string",
  "student": {
    "studentName": "string",
    "studentId": "string",
    "major": "string"
  }
}
```
다음과 같은 response body를 보내주기 때문에

```ts
interface StudentVerifyResponse {
  signupToken: string;
  student: {
    studentName: string;
    studentId: string;
    major: string;
  }
}
...
const response = await axios.post<AxiosResponse<StudentVerifyResponse>>(SERVER_URL + API_PATH.SIGNUP_VERIFY, verifyInfo);
```
이렇게 작성해 주시면 `response?.data?.data` 와 같이 옵셔널 체이닝을 사용하지 않을 수 있습니다!

2023-09-21 03:02 UTC, ho991217 commented on src/pages/signup/verify.tsx
> +         const response = await axios.post(SERVER_URL + API_PATH.SIGNUP_VERIFY, verifyInfo);
서버 베이스 url 같은 경우 `index.tsx`에 전역으로 설정되어있기 때문에 빼주셔도 됩니다!
```suggestion
         const response = await axios.post(API_PATH.SIGNUP_VERIFY, verifyInfo);
```

2023-09-21 03:02 UTC, ho991217 commented on src/pages/signup/verify.tsx
> +   };
name 속성을 이용해서 하나의 handler로 처리해주신 것 좋네요! 👍👍👍

2023-09-21 05:54 UTC, ho991217 approved these changes

2023-09-21 05:54 UTC, merged