feat/8(구예원)회원가입약관동의페이지
EveryUniv/next-student-council-frontend pull request #17
Opened 2023-09-20 04:53 UTC by 9ye1

**What is this PR?**
- 회원가입 약관동의 페이지 (화면, 체크박스 값 저장, 다음화면으로 이동)

**What has changed?**
- 

**A notice to reviewers...**
- 설정관련오류가 많이 났는데 제 환경에서만 그런 것 같아서 바뀐 환경설정들은 커밋하지 않고 페이지만 올렸습니다. 
다른 환경에서도 실행이 잘 되는지 확인부탁드립니다!

closes #

2023-09-20 07:09 UTC, sy-paik reviewed
reviewer나 assignees, label... 들도 다 추가해주셔야될 것 같아요!

2023-09-21 03:04 UTC, ho991217 commented
라우터에 페이지 연결이 없네요!

2023-09-21 03:39 UTC, ho991217 requested changes
전반적으로 추가되어야하는 부분들이 많은것같습니다!

1. 전체 동의 버튼
2. 라우트 등록

2023-09-21 03:39 UTC, ho991217 commented on src/pages/signupOne.tsx
> +      if (agreeCheck[0] === true && agreeCheck[1] === true && agreeCheck[2] === true) {
`if(agreeCheck[0] === true)`는 `if(agreeCheck[0])`과 동일하죠!

```suggestion
      if (agreeCheck[0] && agreeCheck[1] && agreeCheck[2]) {
```

2023-09-21 03:39 UTC, ho991217 commented on src/pages/signupOne.tsx
> +            </div>
이렇게 반복되는 컴포넌트는 분리합시다!

2023-09-21 03:39 UTC, ho991217 commented on src/pages/signupOne.tsx
> +   const nexthandle = () => {
다른곳은 camel case로 작성해주셨는데 여긴 아니네요!
```suggestion
   const nextHandle = () => {
```

2023-09-21 05:55 UTC, ho991217 approved these changes

2023-09-21 05:55 UTC, merged