feat/8(구예원) 라우터 설정/ 전체동의 구현
EveryUniv/next-student-council-frontend pull request #22
Opened 2023-09-22 10:33 UTC by 9ye1

**What is this PR?**
- 라우터 설정/ 전체동의 구현

**What has changed?**
- 동의완료 버튼 클릭 시 세 조건을 확인한 후 회원가입/학생인증 페이지로 넘어가기
- 전체동의하기 버튼 구현 (체크 시 3조건 모두 true, 세 조건이 모두 true일 때만 전체 체크 비활성화 가능)

**A notice to reviewers...**
- 전체동의버튼 기능 코드가 조금 지저분한 것 같아서 더 간단한 방법이 있다면 소개부탁드립니다!

closes #8

2023-09-23 06:43 UTC, ho991217 requested changes

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
> +               </label>
이렇게 반복되는 컴포넌트는 분리해주세요!

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
> +   const [agreeCheck, setAgreeCheck] = useState([false, false, false]);
배열로 관리하신 부분이 좋네요! 👍

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
>     const handleCheckboxChange = (index: number) => {
이벤트를 다루는 함수가 아니므로 on- 의 이름을 쓰면 좋을 것 같네요
```suggestion
   const onChangeCheckbox = (index: number) => {
```

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
> +      if (index === 3) {
index보단 id나 name 속성을 이용하시면 어떨까요?

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
> +         setAgreeCheck(newAgreeCheck);
체크박스 하나의 change를 담당하는 함수와 전체 동의 체크를 담당하는 함수로 책임 분리를 하면 더 깔끔할 것 같습니다

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
>     const nextHandle = () => {
handler가 아니기 때문에 goNext(), next() 등의 동사형으로 써주세요~

2023-09-23 06:43 UTC, ho991217 commented on src/pages/signup/terms.tsx
>           alert('약관에 동의해야 회원가입이 가능합니다.');
window 객체의 alert이 아닌 useAlert 훅의 alert을 사용해주시면 좋을 것 같습니다!

2023-09-23 13:32 UTC, sy-paik commented on src/pages/signup/terms.tsx
>  import { useState } from 'react';
```suggestion
import { React, useState } from 'react';
```
이렇게 한줄로 줄일 수 있을 것 같아요!

2023-09-23 13:32 UTC, sy-paik commented on src/pages/signup/terms.tsx
> +               <label>
저도 label과 input의 checkbox 형태는 안에 텍스트만 다를뿐 동일해서 컴포넌트화하는게 좋을 것 같습니다

2023-09-25 01:34 UTC, ho991217 commented on src/pages/signup/terms.tsx
>  import { useState } from 'react';
React는 default export에요!
```suggestion
import React, { useState } from 'react';
```

2023-09-25 05:49 UTC, 9ye1 commented on src/pages/signup/terms.tsx
>     const handleCheckboxChange = (index: number) => {
네 적용하겠습니다~!

2023-09-25 06:12 UTC, 9ye1 commented on src/pages/signup/terms.tsx
> +         setAgreeCheck(newAgreeCheck);
네! 적용했습니당

2023-09-25 07:21 UTC, 9ye1 commented on src/pages/signup/terms.tsx
> +      if (index === 3) {
네! name 써서 수정했습니다~!

2023-09-27 00:33 UTC, ho991217 approved these changes

2023-09-27 00:33 UTC, merged