feat: 회원가입 회원 정보 페이지
EveryUniv/next-student-council-frontend pull request #29
Opened 2023-09-28 15:50 UTC by sy-paik

**What is this PR?**
- Pull Request에 대한 설명
- 회원가입 페이지의 회원 정보 페이지

**What has changed?**
- 바뀐 부분에 대한 설명
- 학생 인증에 성공하면 회원 정보 입력 페이지로 이동합니다.
- Input 컴포넌트에 필요한 props를 추가하였습니다.

**A notice to reviewers...**
- 중점적으로 리뷰할 부분
- 닉네임, 휴대폰 인증, 인증코드 확인, 회원가입 버튼이 잘 동작하는지 확인해주세요.
- 닉네임, 휴대폰 인증, 인증코드 확인을 위한 메시지가 적절하게 뜨는지 확인해주세요.

closes #19

2023-09-29 11:03 UTC, ho991217 requested changes

2023-09-29 11:03 UTC, ho991217 commented on src/api/axios-interface.ts
> +}
학생 인증외에는 사용하지 않을 interface이기 때문에, 해당 컴포넌트나 페이지 파일안에 포함시켜도 될 것 같습니다!

2023-09-29 11:03 UTC, ho991217 commented on src/components/ui/input/index.tsx
> +            ${className}::placeholder text-gray-600 mb-2`}
className이 가장 마지막에 있다면 사용자가 스타일을 덮어쓰기하기 쉽지 않을까요?
그리고 앞뒤로 공백이 없기 때문에 스타일이 먹히지 않을 것 같네요!

2023-09-29 11:03 UTC, ho991217 commented on src/components/ui/input/index.tsx
> +            onChange={onChange}
`...props`에 포함시키지 않고 따로 작성해주신 이유가 뭔가요?

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +   console.log(data);
console log들은 삭제해주세요!
```suggestion

```

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +   localStorage.setItem('signup-token', data.signupToken);
localstorage 키와 같은 것들은 상수로 관리해주셔야합니다!
`constant.tsx`에 없다면 추가해주세요!

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
귀찮고 양 많은 내용인데 고생많으셨습니다!

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +      console.log(formData);
데이터 처리하는 부분은 어디 있을까요?.??

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +               <button className={'ml-[-3rem] text-blue-600'}>확인</button>
input은 self-closing tag죠!

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +            <button className={'ml-[-5rem] text-blue-600'}>중복확인</button>
그리고 버튼도 만들어져있는 컴포넌트 사용하시면 됩니다!

2023-09-29 11:03 UTC, ho991217 commented on src/pages/signup/info.tsx
> +   localStorage.setItem('signup-token', data.signupToken);
`data`가 없으면 오류가 나네요!

2023-09-29 11:03 UTC, ho991217 commented on tailwind.config.js
> +         },
어떤 내용인가요???

2023-09-29 11:03 UTC, ho991217 commented
연휴인데도 고생 많으셨습니다!

2023-10-01 15:16 UTC, 9ye1 approved these changes
코드 잘 봤습니다! 고생하셨습니다🙂🙂

2023-10-02 07:37 UTC, ho991217 approved these changes

2023-10-02 07:39 UTC, merged