feat: 청원 게시판 (게시판 보기)
EveryUniv/next-student-council-frontend pull request #30
Opened 2023-10-03 11:57 UTC by gaeunnlee

**What is this PR?**
- 청원 게시판 페이지

**What has changed?**
- switch문 indent 관련하여 eslint 수정
- 청원 게시판 목록 무한 스크롤 구현

**A notice to reviewers...**
- 스크롤시 글 목록이 알맞게 오는지 확인 부탁드립니다

closes #20

2023-10-04 08:25 UTC, ho991217 requested changes
고생하셨습니다 🥳

2023-10-04 08:25 UTC, ho991217 commented on src/constant.ts
> +   },
주석을 달아주세요!
```suggestion
   PETITION: {
      /** 청원 루트 */
      ROOT: '/petition',
      /** 청원 상세보기 */
      POST: '/petition/:id',
   },
```

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +   });
커스텀 훅으로 분리 가능하지 않을까요?

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +   };
하나의 함수는 하나의 기능만 담당하면 좋을 것 같습니다!

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +      axios.get(`${API_PATH.POST.PETITON}?page=${boardPage}&size=10&sort=id,desc`).then(({ data }) => {
`.then()`은 가독성을 저하시킬 수 있기 때문에 `async-await`구문을 사용합시다!

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +      </>
만들어져있는 `Board`컴포넌트를 활용하면 좋을 것 같아요!

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +      axios.get(`${API_PATH.POST.PETITON}?page=${boardPage}&size=10&sort=id,desc`).then(({ data }) => {
`query string`도 상수화하면 가독성을 늘릴 수 있을 것 같습니다

2023-10-04 08:25 UTC, ho991217 commented on src/pages/petition/index.tsx
> +      axios.get(`${API_PATH.POST.PETITON}?page=${boardPage}&size=10&sort=id,desc`).then(({ data }) => {
에러처리 부탁드립니다~!

2023-10-04 08:25 UTC, ho991217 commented on src/pages/signup/info.tsx
>        }
`switch` 문을 이용해서 하나의 함수에서 change 이벤트를 핸들링 해 준 것은 좋은 아이디어 같습니다!

```typescript
const handleChange = <E, T>(e: ChangeEvent<E>, setter: Dispatch<SetStateAction<T>>) => {
   setter(e.target.value);
}
// ...
return <input onChange={(e) => handleChange<HTMLInputElement, string>(e, setPasswordConfirm)} />;
```

과 같이 작성해서 setter를 넘겨주는 방법이 있을것 같은데, 어떻게 생각하시나요?

2023-10-04 08:25 UTC, ho991217 commented on src/pages/signup/info.tsx
> +            setphoneNumber(value);
`setPhoneNumber` 또는 `setTel`이 적절할 것 같습니다!

2023-10-06 08:14 UTC, 9ye1 approved these changes
코드 잘 봤습니다!! 참고해서 petition/[id].tsx 수정해서 pr올리겠습니당

2023-10-06 11:31 UTC, sy-paik approved these changes

2023-10-06 11:31 UTC, sy-paik commented on src/pages/signup/info.tsx
>        }
> `switch` 문을 이용해서 하나의 함수에서 change 이벤트를 핸들링 해 준 것은 좋은 아이디어 같습니다!
> 
> ```ts
> const handleChange = <E, T>(e: ChangeEvent<E>, setter: Dispatch<SetStateAction<T>>) => {
>    setter(e.target.value);
> }
> // ...
> return <input onChange={(e) => handleChange<HTMLInputElement, string>(e, setPasswordConfirm)} />;
> ```
> 
> 과 같이 작성해서 setter를 넘겨주는 방법이 있을것 같은데, 어떻게 생각하시나요?

아 이거 제부분에서 indent 때문에 같이 올려주신 것 같은데 반영해서 같이 올리겠습니다

2023-10-06 11:31 UTC, sy-paik commented on src/pages/signup/info.tsx
>        }
@ho991217 말씀해주신 방법으로 시도해보긴 했는데 setter를 Dispatch<setStateAction<IUserRegistration>> 타입으로 판단해서 signupInfo의 nickname이나 password 속성에 접근이 안되네요 ㅠ

2023-10-12 09:23 UTC, ho991217 approved these changes

2023-10-12 09:23 UTC, ho991217 commented on src/hooks/useInfiniteScroll.ts
> +         const { data } = await axios.get(`${api}?page=${boardPage}&size=10&sort=id,desc`);
업데이트 된 develop 브랜치로부터 최신화 해 주시고 query string도 상수로 써 줍시다

2023-10-12 09:23 UTC, ho991217 commented on src/pages/petition/index.tsx
> +   const { list, isLoading, bottom } = useInfiniteScroll<IPetitionPost>(API_PATH.POST.PETITON);
좋네요! 👍

2023-10-12 09:23 UTC, ho991217 commented on src/pages/petition/index.tsx
> +         </ul> */}
주석은 제거하고 올리자구요
```suggestion
```

2023-10-12 09:25 UTC, merged