feat: 청원 글쓰기 페이지
EveryUniv/next-student-council-frontend pull request #36
Opened 2023-11-01 17:42 UTC by sy-paik

**What is this PR?**
- react-quill 을 이용한 청원 글쓰기 페이지를 구현하였습니다.

**What has changed?**
- 청원 글 작성을 위한 라우터 설정 및 useApi 훅을 사용하였습니다.
- react-quill 을 따로 컴포넌트화하였습니다.
- 이미지 추가 및 삭제하는 핸들러를 hook으로 분리하였습니다.
- content-type option을 추가하였습니다.

**A notice to reviewers...**
- react-quill 에서 모듈이 어떤게 필요한지 몰라서 기본으로 굵기, 밑줄, 사이즈 등을 추가했는데 한번 확인부탁드립니다. 불필요한 부분이 있으면 빼겠습니답

closes #

2023-11-02 04:25 UTC, ho991217 requested changes
수고하셨습니다!

2023-11-02 04:25 UTC, ho991217 commented on src/components/common/editor/index.tsx
> +const TextEditor: React.FC<TextEditorProps> = ({ onChange, value }) => {
React.FC 타입 선언은 지양하시는 것이 좋습니다

[관련 문서] https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

2023-11-02 04:25 UTC, ho991217 commented on src/components/common/editor/index.tsx
> +  onChange: (value: string) => void;
event function이기 때문에 인자로 이벤트를 받아주셔야합니다!!
```suggestion
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
```
Input 요소가 맞는지 모르겠지만,,, 그렇게 작성하심 됩니다

2023-11-02 04:25 UTC, ho991217 commented on src/components/common/editor/index.tsx
> +   );
연산된 값이 없어보이는데, 메모이제이션을 해주신 이유가 있나요?

2023-11-02 04:25 UTC, ho991217 commented on src/hooks/useApi.ts
> +   multipart?: boolean;
제가 고려 못한 부분에 대한 좋은 업데이트 같습니다! 
contentType으로 작성해주시면 다른 유형에 대해서도 사용할 수 있을 것 같습니다!

```suggestion
   type contentType = 'multipart/formed-data' | 'Application/json' | 'Application/x-www-form-urlencode';
   contentType?: contentType
```

2023-11-02 04:25 UTC, ho991217 commented on src/hooks/useImageHandler.tsx
> +         }
```suggestion
         const fileList = [...formInfo.files, ...imageList];
         const urlList = [...imageUrls, ...imageList.map(URL.createObjectURL)];
```
`for 문`없이 표현 가능하겠네요! 명령형 프로그래밍과 선언형 프로그래밍에 대해 알아보시면 좋을 것 같습니다...!!

2023-11-02 04:25 UTC, ho991217 commented on src/hooks/useImageHandler.tsx
> +   const addImage = (e: ChangeEvent<HTMLInputElement>, formInfo: IFormInfo, setFormInfo: React.Dispatch<React.SetStateAction<IFormInfo>>) => {
interface나 type으로 선언하고 사용하는 편이 낫지 않을까요?

2023-11-02 04:25 UTC, ho991217 commented on src/hooks/useImageHandler.tsx
> +   const deleteImage = (id: number, imageUrls: string[], formInfo: IFormInfo, setFormInfo: React.Dispatch<React.SetStateAction<IFormInfo>>) => {
마찬가지로 인터페이스나 타입으로 만들어서 사용하면 더욱 읽기 편한 코드가 될 것 같습니다

2023-11-02 04:25 UTC, ho991217 commented on src/hooks/useImageHandler.tsx
> +const useImageHandler = () => {
이 훅이 해주는 역할을 이름을 통해 더 명확히 해주면 좋을 것 같네요!
handler와 같은 일반적인 표현은 지양합시다! 😎

2023-11-02 10:00 UTC, 9ye1 approved these changes
코드 잘 봤습니다 수고하셨습니다!!

2023-11-07 01:37 UTC, gaeunnlee commented
수고하셨습니다!

2023-11-07 01:39 UTC, gaeunnlee reviewed
수고하셨습니다!

2023-11-08 13:14 UTC, gaeunnlee approved these changes

2023-11-08 13:14 UTC, gaeunnlee approved these changes

2023-11-08 13:15 UTC, gaeunnlee approved these changes

2023-11-08 13:15 UTC, gaeunnlee approved these changes

2023-11-08 14:35 UTC, ho991217 approved these changes

2023-11-08 14:35 UTC, merged