feat: 회원 정보 페이지
EveryUniv/next-student-council-frontend pull request #69
Opened 2024-01-23 07:23 UTC by gaeunnlee

**What is this PR?**
- 마이페이지 기본 화면, 비밀번호 확인 화면, 회원정보 수정 화면을 작성하였습니다.

**What has changed?**
- `/mypage` 화면 작성
  - 마이페이지 상단 회원정보를 `MyPageLayout` 컴포넌트로 분리하였습니다.
  ![image](https://github.com/EveryUniv/next-student-council-frontend/assets/88781949/67746852-e60e-4de0-8eab-474967effcac)

- `/mypage/password` 화면 작성
  - 회원정보 수정 페이지를 들어가기 전 비밀번호를 확인하는 페이지입니다.
  - 비밀번호 확인 절차만 필요하여 `MyPageLayout`에서 `getStudentId`를 통해 가져온 학번과 해당 화면의 비밀번호 input 값을 body에 담아 로그인 api로 비밀번호를 확인하도록 하였습니다.

- `/mypage/edit` 화면 작성
  - 회원정보 수정 페이지입니다.
  - 커밋이 많아질 것 같아 유효성 검사와 api 연결은 아직 하지 않았습니다!
    - 피드백 반영 후 나머지 부분 마저 작성해서 이 브랜치에 push 하겠습니다.
  - 중복되는 input이 많아 객체 데이터를 매핑하는 방식으로 작성하였습니다.
    - `nickname`과` major` 값은 회원정보 fetch 후 가져와야 해서 함수로 작성하였습니다.
    - 객체 데이터가 복잡해진 것 같아 이 방법이 맞는지 궁금합니다🥲

```typescript
interface IFormInfo {
   title: string;
   inputType: string;
   placeholder?: string;
   button?: string;
   bigButton?: string;
   defaultMessage?: string;
   errorMessage?: string;
   successMessage?: string;
   validationCheck?: boolean;
   validation?: null | boolean;
}
...
                        {box.map((item: IFormInfo) => (
                           <div key={item.title}>
                              <Label text={item.title} />
                              <InputBox>
                                 <InputText
                                    type={item.inputType}
                                    placeholder={item.placeholder}
                                    disabled={item.title === '학과 및 재학 여부'}
                                 />
                                 {item.button && <InputButton text={item.button} />}
                                 {item.validationCheck && item.validation !== undefined && (
                                    <ValidationIcon validation={item.validation} />
                                 )}
                              </InputBox>
                              {item.bigButton && <InputButton text={item.bigButton} type='big' />}
                              {item.defaultMessage && <Message text={item.defaultMessage} />}
                           </div>
                        ))}
                     </Box>
                  ))}

...
const defaultFormInfo = ({ nickname, major }: { nickname: string; major: string }) => [
   [
      {
         title: '닉네임',
         inputType: 'text',
         placeholder: nickname,
         bigButton: '변경',
         validation: null,
         validationCheck: true,
         successMessage: '사용 가능한 닉네임입니다',
         errorMessage: '사용 불가능한 닉네임입니다',
      },
   ],
   [
      {
         title: '비밀번호 변경',
         inputType: 'password',
         placeholder: '새로운 비밀번호를 입력해주세요',
         validation: null,
         validationCheck: true,
         defaultMessage: '비밀번호는 영문과 숫자를 1자 이상 포함하는 8-16 자리여야 합니다.',
         errorMessage: '비밀번호는 영문과 숫자를 1자 이상 포함하는 8-16 자리여야 합니다.',
      },
      {
         title: '비밀번호 재확인',
         inputType: 'password',
         placeholder: '새로운 비밀번호를 재입력해주세요',
         validation: null,
         validationCheck: true,
         bigButton: '확인',
         errorMessage: '사용 불가능한 닉네임입니다',
         successMessage: '비밀번호가 변경되었습니다.',
      },
   ],
   [
      {
         title: '학과 및 재학 여부',
         inputType: 'text',
         placeholder: major,
         button: '변경',
      },
   ],
...
];

``` 

  ![image](https://github.com/EveryUniv/next-student-council-frontend/assets/88781949/e8675494-e0ba-4458-990d-f413c4ce1fb5)

**A notice to reviewers...**
  - 회원정보 수정 페이지 코드가 복잡해보이지 않는지 궁금합니다..! (`/pages/mypage/edit`)

closes #47

2024-01-24 03:20 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +   defaultMessage?: string;
validation 관련 프로퍼티는 interface를 분리하는 게 좋을 것 같아요.
union type이나 intersection type으로 관리해도 괜찮습니다.

2024-01-24 03:21 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +                        {box.map((item: IFormInfo) => (
스타일 차이이긴 한데 저는 `{title, inputType, placeholder}: IFormInfo` 이런 식으로 구조 분해 할당해주는 걸 선호합니다!

2024-01-24 04:38 UTC, chchaeun commented on src/pages/mypage/index.tsx
> +         <>
불필요한 Fragement 인것 같습니다!

2024-01-24 04:38 UTC, chchaeun approved these changes

2024-01-24 04:38 UTC, chchaeun approved these changes
고생하셨습니다 :)

2024-01-24 08:14 UTC, developerChans requested changes
이전 Build가 Failed 되어서 처리완료되면 제가 Merge하겠습니다.

2024-01-27 00:30 UTC, gaeunnlee commented
- 피드백 반영 후 회원정보 수정 페이지를 마저 작업했습니다!
- `학과 및 재학 여부`와` 휴대폰번호 인증`은 API가 준비되면 작업할 예정입니다!
- input에 대한 `onClick` `onChange` 이벤트를 객체에 담아봤습니다
  - 코드가 많이 길어진 것 같은데 괜찮은지 봐주시면 감사하겠습니다🥹

2024-01-28 20:21 UTC, gutanbug commented
- 현재 SMS 인증을 사용하는 API는 테스트가 끝나 개발서버에서 사용 가능합니다.
- 학과 및 재학여부 API는 단국대학교 재학생 인증 확인을 위한 데이터 값 추가 및 프로필 사진 데이터 크롤링으로 인해 작업이 조금 걸리 것 같습니다. 해당 API는 마무리 되는대로 깃 이슈 및 슬랙에 공지하겠습니다.

최대한 작업 빨리 끝내겠습니다! 조금만 기다려주세요 😂

2024-01-29 07:53 UTC, chchaeun approved these changes
고생하셨습니다 :)

2024-01-29 07:53 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +                                 <InputBox>
Input 컴포넌트를 분리하는 게 좋을 것 같아요. 분리한 뒤에 form 관련 내용을 넘겨주고 렌더링만 해주도록 추상화하면 깔끔할 것 같습니다

2024-01-29 07:53 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +                                    {validation !== undefined && (
validation 관련 컴포넌트도 너무 늘어져있어서 묶어서 추상화해주는 게 좋을 것 같아요

2024-01-29 07:53 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +                           ({
input 컴포넌트를 추상화하면 props 부분은 구조분해 하지 말고 한번에 넘겨주는 게 좋을 것 같습니다

2024-01-29 07:53 UTC, chchaeun commented on src/pages/mypage/edit.tsx
> +            onClick: async () => {
이 부분 익명함수들이 너무 늘어져있어서, 객체를 아예 밖으로 빼주시거나 함수를 선언해서 접근할 수 있게 해주세요!

2024-01-29 07:53 UTC, chchaeun commented on src/data/mypage/edit/defaultFormInfo.ts
> +export const defaultFormInfo = ({
form 로직과 validation 로직 분리해서 객체화한 거 좋아요 👍👍

2024-01-29 07:53 UTC, chchaeun approved these changes
고생하셨습니다 :)

2024-01-30 09:10 UTC, merged