feat: 재학 여부 업데이트 페이지 & 모달
EveryUniv/next-student-council-frontend pull request #71
Opened 2024-02-06 13:32 UTC by gaeunnlee

**What is this PR?**
- 회원 정보 수정 페이지를 리팩토링하였습니다.
- 학교 계정으로 로그인하여 재학 여부를 갱신할 수 있는 회원 정보 업데이트 페이지를 작성하였습니다.
- 로그인 후 첫 화면에서 회원 정보 업데이트 페이지로 이동하는 모달이 실행되도록 하였습니다.

**What has changed?**
- 기존에는 회원정보 페이지에서 직접 `<InputText />`에 onChange 이벤트를 작성하였는데, `<InputText />` 컴포넌트에 `setInputsValue`와 `setOnChangeEvent`만 전달하고 컴포넌트 안에서 onChange 이벤트 처리하도록 수정하였습니다.
- 회원 정보 수정 페이지의 onClick 이벤트 함수를 따로 정의하였습니다.
- 회원의 프로필 이미지와 재학 여부 데이터를 추가하였습니다.
- 회원 정보 업데이트 페이지와 모달을 작성하였습니다.
  1. 로그인 후 메인페이지로 이동하면 `useFetchMyInfo` hook을 통하여 재학 여부 (`dkuChecked`)를 가져온 후 `enrollment` (재학 여부, 전역 상태)에 업데이트
  2. 라우터 다음으로 최상위 레이아웃인 `<DefaultLayout />`에서 pathname이 변경될 때마다 `enrollment` 값을 확인하여 모달 실행
- 기존 `useModal()`에 `disableCancle` props를 추가하여 Overlay를 눌러도 닫히지 않게 하였습니다.

**A notice to reviewers...**
- 전역으로 모달을 띄우는 로직을 처음으로 작성해보는데 이 방법이 맞는지 피드백해주시면 감사하겠습니다..!
- 재학 여부 false인 테스트 계정 만들어지는대로 다시 알려드리겠습니다!

2024-02-08 00:05 UTC, chchaeun commented on src/hooks/useFetchMyInfo.tsx
> +            setEnrollmet(data.dkuChecked);
오타있습니다!

2024-02-08 00:05 UTC, chchaeun commented on src/hooks/useFetchMyInfo.tsx
> +   const setEnrollmet = useEnrollmentStore((state) => state.setEnrollment);
`const {setEnrollment} = useEnrollmentStore()`로 바꿀 수 없을까요?

2024-02-08 00:05 UTC, chchaeun commented on src/layouts/DefaultLayout.tsx
> +   const enrollment = useEnrollmentStore((state) => state.enrollment);
`const {enrollment} = useEnrollmentStore();`

여기도 마찬가지로 이렇게 작성할 수 있을 것 같아요

2024-02-08 00:05 UTC, chchaeun commented on src/components/ui/modal/DefaultModal.tsx
> +   const alertModal = (content: string) => (<div>{content}</div>) as React.ReactNode;
리액트 노드 컴포넌트는 파스칼 케이스 네이밍 지켜주세요!

그리고 hook 안에서 컴포넌트를 만드는 구조가 명료하지 않은 것 같아요.
Modal 관련 컴포넌트를 하나 빼고, hook을 해당 컴포넌트 안에 묶은 다음 `DefaultLayout`과 같은 컴포넌트에 렌더링하는 건 어떨까요?

2024-02-08 00:05 UTC, chchaeun commented on src/components/ui/modal/DefaultModal.tsx
> +         disableCancle: disableCancle,
key, value 값이 같은 경우 value는 생략 가능합니다!
```
{   
    title: "알림",
    disableCancle
}
```

2024-02-08 00:06 UTC, chchaeun requested changes
고생하셨습니다! 수정 후 푸시하면 한번 더 확인할게요

2024-02-08 00:06 UTC, chchaeun requested changes
고생하셨습니다! 수정 후 푸시하면 한번 더 확인할게요

2024-02-11 17:34 UTC, gaeunnlee commented
모달 컴포넌트 분리해봤는데 확인부탁드립니다!!

2024-02-12 04:54 UTC, chchaeun commented on src/components/ui/modal/Modal.tsx
> +   return <></>;
컴포넌트를 분리하라고 말씀 드렸던 게 <Modal> 자체를 렌더링하는 컴포넌트가 있었으면 좋겠다는 의미였는데 해당 컴포넌트는 provider와 모달 사용부를 연결해주는 중간다리 역할을 하고 있군요! 이 경우는 jsx를 렌더링하고 있지 않기 때문에 hook 형태로 만드는 게 조금 더 적합할 것 같습니다. provider 내부에 해당 코드들을 관리하는 것도 괜찮을 것 같구요!!
```suggestion
   return <></>;
```

2024-02-12 04:56 UTC, chchaeun approved these changes
복잡한 로직인데 개발하느라 고생하셨습니다 : ) 우선 피드백은 남겨두긴 했는데 수정 여부는 판단하에 결정하면 될 것 같아요!!

2024-02-12 12:05 UTC, gaeunnlee commented
넵 피드백 감사합니다!

2024-02-12 12:05 UTC, merged